### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by betterteam** [maslab-ufrgs/TAP_GA_QL#1]
Can I ask you a question about the code?

When I am trying to use your code to do some experiments. After I ran experiment.py and runExperiment_GA_QL.py  I found an error which is 
TypeError: run_ga_ql() takes exactly 11 arguments (9 given).

Could you please tell me what is the reason of that error? Thank you very much.

**Comment by hoarf** [comment]
I was not the first author of this code. I just made some modifications so I don't know all the use cases, and have never used run\* scripts. The way I'm using it is creating an experimentConfig.ExperimentConfig instance and then calling run() on it.

I'll probably remove all the run\* scripts at some point in the near future.

Here's an example:

https://github.com/hoarf/experimento-ga-ql/blob/72b54d77793bbc4d5935c7ffbc9129815eb1dcaf/tarefa.py

You can check the ExperimentConfig **init** method to see all the possible parameters, but all of them have a default value that is assumed if you don't replace them.

**Comment by betterteam** [comment]
Thank you very much for your reply.

When I was trying to run tarefa.py, it also gave an error which is
TypeError: **init**() got an unexpected keyword argument 'outputtype'.

By the way, can you run the minimalExample.py without having an error?

**Comment by hoarf** [comment]
Yeah the tarefa.py file was deleted because it is supposed to be a list of experiments configs that you want to run. So the idea was everyone should have their own 'tarefa.py' (tarefa means taks in portuguese btw)

It fails because the flag names was slightly changed between when the file existed and now. Check the **init** method to see which ones are valid

**Comment by hoarf** [comment]
Yeah the minimal example Is also not gonna work. I'll get rid of this run\* scripts on the next commit.

These are the working set of parameter now:

def **init**(self, printLinkCosts=False, printDriversPerLink=False,
             printPairOD=False,
             generations=10, population=100, repetitions=1,
             experimentType=1, elite_size=5, group_sizes=[1], alphas=[.9],
             decays=[.99], crossovers=[0.2], mutations=[0.001], ks=[8],
             interval=[None], network = ORTUZAR_NETWORK,
             network_od = ORTUZAR_NETWORK_OD)

Depending on how comfortable you are with python, your best bet is probably start with:

``` python
from ExperimentConfig import ExperimentConfig

e = ExperimentConfig()

e.run()
```

And adding some parameters as you go

**Comment by betterteam** [comment]
Thank you very much for your kind explanation. I'll try it again.

**Comment by hoarf** [comment]
No worries. Thanks for pointing out the confusion with the run scripts

**Comment by hoarf** [comment]
Closing the issue
